language: node_js

# Node versions: https://node.green/
matrix:
  include:
    - os: windows
      env: CXX=g++-4.9
      node_js: "13.3.0"
    - os: linux
      env: CXX=g++-4.9
      node_js: "12.4.0"

os:
  - osx

env:
  - CXX=clang

node_js:
  - "12.10.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false
dist: precise
cache: npm

before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"
  - "npm install coveralls"

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"

  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

script:
  - if [[ ${NODE_ONLY} == true ]]; then
      npm run build-test:ci;
    else
      npm run ci;
    fi
